//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具自动生成。
//     运行时版本:4.0.30319.18034
//
//     手动修改可能导致行为异常，重新生成后也会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageTool.GrabImage.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }
    }
}
